# Generated by Django 4.2.7 on 2025-02-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='country',
            field=models.CharField(default='netherlands', max_length=30),
            preserve_default=False,
        ),
    ]
