# Generated by Django 4.2.7 on 2025-02-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='country',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
