# Generated by Django 4.2.7 on 2025-03-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_country_alter_place_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
