version: '3.4'

networks:
  homebase_network:
  default:
    driver: bridge

services:

  ancients:
    build:
        context: $HOME/my_docker/ancients
        dockerfile: Dockerfile
    container_name: ancients
    image: ancients:latest
    networks:
      - homebase_network
    ports:
      - 8014:8000
    expose:
      - 8014
    restart: always
    volumes:
    # this is where the app will find the sqlite3 database
      - $HOME/shared:/shared
      - /var/log:/data

